name = "MembranePlotting"
uuid = "1b91c9d9-a9ff-4de1-9882-2ff984747969"
authors = ["Will <sypheren@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
